version: '3'
services:
  app:
    image: pang-app:0.4
    ports:
      - "5000:5000"
    depends_on:
      - postgres_db
    env_file:
      - .env
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: wltjd123
      POSTGRES_DB: jiseong_db
      POSTGRES_USER: hyoshincopy
    ports:
      - "5432:5432"
