version: '3'
services:
  app:
    image: pang-app:1.9
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
    env_file:
      - .env

  mariadb:
    image: mariadb:latest
    container_name: mariadb_db
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"

  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
