"""empty message

Revision ID: 021cbc442816
Revises: e522547a3227
Create Date: 2023-07-26 18:02:28.549016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021cbc442816'
down_revision = 'e522547a3227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_valid', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_auth', schema=None) as batch_op:
        batch_op.drop_column('is_valid')

    # ### end Alembic commands ###
