"""empty message

Revision ID: 18db5429fa6b
Revises: 5d38965cb3a7
Create Date: 2023-07-27 16:35:46.444080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18db5429fa6b'
down_revision = '5d38965cb3a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.drop_column('views')

    # ### end Alembic commands ###
