"""empty message

Revision ID: 39ff0a91d9d9
Revises: 
Create Date: 2023-07-24 11:11:19.148598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ff0a91d9d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_id', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['login_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('login_id')

    # ### end Alembic commands ###
