"""empty message

Revision ID: 5d38965cb3a7
Revises: 
Create Date: 2023-07-27 15:35:27.555911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d38965cb3a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like_board', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'board', ['board_id'], ['id'])
        batch_op.drop_column('table_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like_board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
