"""empty message

Revision ID: dc00fb8f5c58
Revises: 737e62958cb4
Create Date: 2023-07-28 22:10:00.518521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc00fb8f5c58'
down_revision = '737e62958cb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like_board', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('board_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_constraint('like_board_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('like_board_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'board', ['board_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like_board', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('like_board_ibfk_2', 'board', ['board_id'], ['id'])
        batch_op.create_foreign_key('like_board_ibfk_1', 'user', ['user_id'], ['id'])
        batch_op.alter_column('board_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
